Feature/reservoirs mvp
parflow/parflow pull request #492
Opened 2023-09-21 02:48 UTC by westb2

Not yet ready for review! Making several final edits and going through commenting pull request for clarity. Will notify when ready.

2023-09-21 02:59 UTC, westb2 commented on docker/dev/Dockerfile
I would like my docker workflow in the main branch because I believe we should have an image to do dev from, however given that the release image inherits some stuff from here and I want this image to build parflow with the debugger enabled I believe maybe we need a third image. Figured I would open up the disussion.

2023-09-27 22:40 UTC, westb2 commented
Just realized I will need to figure out how to make reservoirs.names optional or this breaks our test suite

2023-09-28 21:29 UTC, westb2 commented
Also, should I check in a test case with this for reservoirs?

2023-09-29 21:52 UTC, smithsg84 commented
Yes, we should have a test case for features.

2023-10-10 17:07 UTC, westb2 commented
Will be uploading an appropriate test case from my set of personal test cases later, then this should be ready

2023-11-23 05:12 UTC, westb2 commented
Pending workflow success this PR is ready for review. Since last time, I have added code to support multiple mpi ranks. I have also added two test cases, one for reservoirs as is and one to confirm the work when parallel processing.

2023-11-28 18:08 UTC, westb2 commented
Just realized at the time of my last comment a push had failed. All changes are in now.

2024-01-24 17:56 UTC, smithsg84 requested changes
Some cleanup fixes and there looks like an issue with multiple processors appending to a shared file.

2024-01-24 17:56 UTC, smithsg84 commented on pftools/python/parflow/tools/builders.py
> +                if unit_name.casefold() in (registered_name.casefold() for registered_name in self.name_registration):
Why is case being removed?   We don't traditionally do that in PF.

2024-01-24 17:56 UTC, smithsg84 commented on test/python/CMakeLists.txt
> +    reservoir_mpi_test
This doesn't look to be tested in parallel; doesn't look like it is testing under MPI.  Needs to be in the PARALLEL_ topo tests.

2024-01-24 17:56 UTC, smithsg84 commented on test/python/reservoir_mpi_test.py
> +sloping_slab.Process.Topology.P = 1
Looks to be hard-coding to a single rank run?

2024-01-24 17:56 UTC, smithsg84 commented on pftools/python/parflow/tools/io.py
> +        self.f = open(self.filename, 'rb+')
This is a Reader why is writing being added?

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/reservoir_package.c
> +      MPI_Comm new_reservoir_communicator;
Will break if MPI is not used.   Need to guard MPI usage.

#ifdef PARFLOW_HAVE_MPI
#else
#endif

The AMPS layer was supposed to hide MPI and do nothing/appropriate when MPI or other parallel layers where not present.   So for things that are not exposed by AMPS we need to guard appropriately or expand the AMPS layer to add the functionality.

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/reservoir_package.c
> +bool subgrid_lives_on_this_rank(Subgrid* subgrid, Grid *grid){
New code should have doxygen comments for methods.

https://github.com/parflow/parflow/blob/master/CONTRIBUTING.md#source-code-documentation

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/reservoir_package.c
> +      MPI_Comm_split(MPI_COMM_WORLD, split_color, current_mpi_rank, &new_reservoir_communicator);
Should use amps_CommWorld for MPI_COMM_WORLD.

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/solver_richards.c
> +    WriteReservoirs("ReservoirsOutput",
Add a key to control writing the output, like the print_wells flag.   We allow users to turn off I/O if they don't want it.

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/reservoir.h
> +#define RESERVOIRDATA_PRINTPHYSICAL  0x0001
Are these flags used somewhere?   I'm not seeing it show up in search.

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/reservoir.h
> +    MPI_Comm mpi_communicator;
MPI_Comm needs to be guarded, may not have MPI in build.

2024-01-24 17:56 UTC, smithsg84 commented on pfsimulator/parflow_lib/solver_richards.c
> +        if (ReservoirDataPhysicalMpiCommunicator(reservoir_data_physical) != MPI_COMM_NULL){
This will break if we build without MPI.

2024-01-24 17:59 UTC, smithsg84 commented
Test build is failing; tests require the C to be clean.   Should not show any errors when building with 

-DCMAKE_C_FLAGS="-Wall -Werror"

/home/runner/work/parflow/parflow/pfsimulator/parflow_lib/problem_phase_source.c:74:60: error: unused variable ‘reservoir_intake_subgrid’ [-Werror=unused-variable]
   74 |   Subgrid          *subgrid, *well_subgrid, *tmp_subgrid, *reservoir_intake_subgrid, *reservoir_release_subgrid;

2024-01-30 08:38 UTC, westb2 commented
Thanks for the review Steve. Sorry to make you leave the Doxygen comment on two in a row - I should have gone back and updated this one after your var-dz review. I've addressed most of your comments but am going to dig a little deeper into the safety of printing that file and ensure the build is passing. I will leave another comment once I have done both those things

2024-03-25 08:01 UTC, westb2 commented
This is ready for review again when you get the time @smithsg84. I think the tests should be passing as well but I don't have permission to run them here. Since you last looked I have made a minor change outside of addressing your comments. Specifically, I added code within parflow to edit the slopes at the reservoir intake cells such that flow would stop. I have functions that I think work for both overland kinematic and overland flow boundary conditions. However, I am actually a bit unclear on what the best way would be to choose which one to do. It seems we might allow people to use both conditions on the same domain. The one place I can find that seems to be doing what I want is in bc_pressure_package.c, where the conditions are set up. Should I do a loop similar to that to check what type of surface each reservoir is on? Thanks in advance.

2024-04-10 00:04 UTC, smithsg84 commented
@westb2 , PF requires code to compile cleanly to merge.   There are errors showing up in the CI tests because of this.   Using 

 -DCMAKE_C_FLAGS="-Wall -Werror -Wno-unused-result -Wno-unused-function"
 
 Will flag the errors.  This is useful because the warnings do show real errors, like the code in reservoir_package.c :
```
void stop_outlet_flow_at_cell_overland_flow(int i, int j, ProblemData* problem_data, Grid* grid){
  Vector      *slope_x = ProblemDataTSlopeX(problem_data);
  Vector      *slope_y = ProblemDataTSlopeY(problem_data);
  Subvector   *slope_x_subvector ;
  Subvector   *slope_y_subvector;
  int index_slope_x;
  int index_slope_y;
  double *slope_x_ptr = SubvectorData(slope_x_subvector);;
  double *slope_y_ptr = SubvectorData(slope_y_subvector);
```

the subvectors are being used without being initialized.

2024-04-19 03:46 UTC, westb2 commented
I think those changes must have been fatfingered in my last intermediate commit, or my test cases never would have passed. Regardless, I checked in a fix as well as added a test case for the overland flow boundary condition. Stuff on my end is building, and my tests are passing. So I think this is ready for review, unless somehow tests are failing in workflow

2024-04-19 03:49 UTC, westb2 commented
As a last update, we now have a key that is required if any reservoirs are in the domain of "Reservoirs.Overland_Flow_Solver" to indicate what solver is being used in the domain. It will throw an error if an unsupported option is provided. Laura and I felt it was the fastest fix that would not require handling weird edge cases or implementing an overcomplicated solution where we looped over the patches

2024-04-19 15:40 UTC, smithsg84 commented
Compile is still failing.

2024-04-23 23:16 UTC, westb2 commented
I am not sure why, but I don't see that error on my local build even with that cmake flag. Not sure why, feels like an unused variable should be a system agnostic warning. I will resolve it, but is there a way to trigger the github build on my own? Don't want to keep bugging you for minor stuff like this.

2024-04-23 23:34 UTC, smithsg84 commented
Are GitHub actions not running if you create a branch?   When I fork the repo and create a branch, pushes to the branch trigger the CI to run.   I thought if you owned the repo you could trigger actions on it.  

https://github.com/westb2/parflow/actions

The merge checks are run as part of the project and the setup was configured to run require a project owner to trigger builds for first time contributors.   Once a contribution is approved, future PR should not require actions.  GitHub setup things this way since people were doing PR's that ran bitcoin like stuff and chewing up compute time.

2024-04-23 23:37 UTC, smithsg84 commented
Warning and errors can be compiler specific.   The Ubuntu 22.04 build is using GCC GNU 11.4.0.

2024-04-24 02:06 UTC, westb2 commented
If not it's fine as I need to figure out how to get those warnings showing on my local anyways, but it would be nice to confirm that the build isn't failing for some other reason on remote before asking for more of your time.

2024-07-23 03:17 UTC, westb2 commented
Hi @smithsg84. Just went through and made sure I had addressed all your changes. There was one comment on a test I wasn't sure what our pattern was (regarding hardcoding number of ranks), but other than that whenever you get a chance to review this again it is ready for you.

2024-07-25 21:28 UTC, smithsg84 requested changes
Did a more careful review and found some other issues.

Is there an assumption about where the domain top is?   It looks like there is an assumption that the top of domain is at the top of the grid    grid_nx - 1?   Maybe I'm confused.

2024-07-25 21:28 UTC, smithsg84 commented on pfsimulator/parflow_lib/reservoir_package.c
> +      #ifdef PARFLOW_HAVE_MPI
General comment , we don't indent preprocessor statements.

2024-07-25 21:28 UTC, smithsg84 commented on pfsimulator/parflow_lib/solver_richards.c
> +                           if (k == (grid_nz - 1))
This appears to be an assumption about where top of the domain is?

2024-07-25 21:28 UTC, smithsg84 commented on pfsimulator/parflow_lib/solver_richards.c
> +                             if (k == (grid_nz - 1))
Assumption about where top of domain is?

2024-07-30 04:40 UTC, westb2 commented
Hi Steve. Thanks for another careful review. I believe I have addressed all of your comments

2024-08-26 21:26 UTC, smithsg84 approved these changes

2024-08-26 21:29 UTC, merged